function AuthLoader() {
  return (
    <>
      <style>{`
        /* 1. Define the integer property for the counter */
        @property --num {
          syntax: '<integer>';
          initial-value: 0;
          inherits: false;
        }

        /* 2. Keyframes for the Percentage Text */
        @keyframes countUp {
          from { --num: 0; }
          to { --num: 100; }
        }

        /* 3. Keyframes for the Progress Bar Width */
        @keyframes loadProgress {
          0% { width: 0%; }
          100% { width: 100%; }
        }

        /* 4. Keyframes for Status Colors (Gray to Color) */
        @keyframes activateText {
          to { color: #d1d5db; /* text-gray-300 */ }
        }
        @keyframes activateDotBlue {
          to { background-color: #60A5FA; /* Blue */ }
        }
        @keyframes activateDotGreen {
          to { background-color: #4ADE80; /* Green */ }
        }

        /* 5. Utility Classes */
        .animate-counter {
          animation: countUp 1s cubic-bezier(0.22, 1, 0.36, 1) forwards;
          counter-reset: num var(--num);
        }
        .animate-counter::after {
          content: counter(num) "%";
        }
        
        .animate-bar-width {
          animation: loadProgress 1s cubic-bezier(0.22, 1, 0.36, 1) forwards;
        }

        /* Status Steps Delays */
        .step-1-text { animation: activateText 0.1s linear 0.2s forwards; }
        .step-1-dot  { animation: activateDotBlue 0.1s linear 0.2s forwards; }
        
        .step-2-text { animation: activateText 0.1s linear 0.6s forwards; }
        .step-2-dot  { animation: activateDotGreen 0.1s linear 0.6s forwards; }
      `}</style>

      <div className="fixed inset-0 z-50 flex flex-col items-center justify-center bg-black">
        {/* Background Glow */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-96 h-96 bg-[#3FC16F] rounded-full mix-blend-multiply filter blur-[128px] opacity-10 animate-pulse"></div>

        <div className="relative w-64 md:w-80 z-10">
          
          {/* Header & Percentage */}
          <div className="flex justify-between items-end mb-2">
            <span className="text-gray-400 font-mono text-xs uppercase tracking-widest">
              Verifying Access
            </span>
            {/* CSS Counter Class applied here */}
            <span className="text-2xl font-bold text-[#4ADE80] font-mono animate-counter">
              {/* Content is generated by CSS ::after */}
            </span>
          </div>

          {/* Progress Bar Container */}
          <div className="h-1 w-full bg-[#171717] rounded-full overflow-hidden border border-gray-800">
            {/* The Moving Bar - Class applied here instead of style={{ width }} */}
            <div
              className="h-full bg-linear-to-r from-[#60A5FA] to-[#4ADE80] shadow-[0_0_10px_rgba(74,222,128,0.5)] animate-bar-width"
            ></div>
          </div>

          {/* Status Steps */}
          <div className="mt-4 space-y-1">
              <div className="flex items-center gap-2 text-xs font-mono text-gray-700 step-1-text">
                  <div className="w-1.5 h-1.5 rounded-full bg-gray-800 step-1-dot"></div>
                  Connecting to server...
              </div>
              <div className="flex items-center gap-2 text-xs font-mono text-gray-700 step-2-text">
                  <div className="w-1.5 h-1.5 rounded-full bg-gray-800 step-2-dot"></div>
                  Validating session...
              </div>
          </div>
        </div>
      </div>
    </>
  );
}

export default AuthLoader